version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7
    container_name: lila-game-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: lila_game
    volumes:
      - mongodb_data:/data/db
    networks:
      - lila-network

  # NestJS Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: lila-game-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      PORT: 3000
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/lila_game?authSource=admin
      JWT_SECRET: your-secret-key-change-this-in-production
      JWT_EXPIRATION: 7d
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongodb
    networks:
      - lila-network
    command: npm run start:dev

  # MongoDB Express (Optional - for database management UI)
  mongo-express:
    image: mongo-express:latest
    container_name: lila-game-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_URL: mongodb://admin:password123@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    depends_on:
      - mongodb
    networks:
      - lila-network

volumes:
  mongodb_data:
    driver: local

networks:
  lila-network:
    driver: bridge